FROM node:16 AS build

WORKDIR /app
COPY . .

RUN npm install
RUN npm run build

FROM python:3.13

WORKDIR /app

COPY . .
COPY --from=build /app/frontend/build/ ./frontend/build/

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 80

CMD ["deployment/entrypoint.sh", "-s"]
