FROM python:3.14.5

WORKDIR /app

ENV UV_PROJECT_ENVIRONMENT=/opt/venv
ENV VIRTUAL_ENV=/opt/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY pyproject.toml ./
RUN pip install --upgrade pip && pip install --no-cache-dir uv
RUN uv sync --no-dev --no-install-project

COPY . .
